### ISSUE TITLE
Could we add some of your fixes to the Marketplace snippets tab?

### ISSUE THREAD

**Issue by theRealPadster** [Florry/Spicetify-default-spotify-fixes-theme#1]
What do you think about adding some of your fixes to the Marketplace Snippets tab?

The playlist arrows have been bugging me for a while, and it looks like you've got some nice fixes here. Adding them as snippets would allow you to use whatever theme you want, with the fixes applied. You could submit a PR on the Marketplace repo or I can just grab them and do it myself if you'd like.

**Comment by Florry** [comment]
Ah yeah this is a good idea, thanks for your input. Adding this as a theme felt kind of wrong and I had not looked into what the snippets actually were but it's a perfect fit. I will fix!

Edit: oh yeah as you wrote you have to submit a pr on the marketplace repo so I guess you can't just add any subjective css "fixes", but I'll submit the playlist arrows at least (and have a look if some of the other things might qualify 😛)

**Comment by Florry** [comment]
Alright, pr opened https://github.com/CharlieS1103/spicetify-marketplace/pull/124

**Comment by theRealPadster** [comment]
Awesome, thank you!
